import { cookies } from "next/headers";
import AuthStore from "./components/Auth";
import Navbar from "./components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("accessToken");

  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <AuthStore isAuth={accessToken} />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
